
sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0: 
        type: com.zaxxer.hikari.HikariDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.5.212:13306/sharding-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
        maxPoolSize: 50
        minPoolSize: 1
      ds1: 
        type: com.zaxxer.hikari.HikariDataSource
        driver-class: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.5.212:23306/sharding-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
        maxPoolSize: 50
        minPoolSize: 1
    config:
      sharding:
        tables:
          t_account:
             actual-data-nodes: ds$->{0..1}.account_$->{0..1}
             database-strategy: 
               standard: 
                 sharding-column: createtime
                 preciseAlgorithmClassName: com.study.mike.sharding.jdbc.sharding.OrderTimePreciseShardingAlgorithm
               #inline:
                 #sharding-column: customer_id
                 #algorithm-expression: ds$->{customer_id % 2}
             table-strategy: 
               inline:
                 sharding-column: id
                 algorithm-expression: account_$->{id % 2}
#             keyGeneratorColumnName: order_id  # 自己注释
             #key-generator-column-name: order_id
             #keyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
        default-data-source-name: ds0
        #defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
        #defaultKeyGenerator:
           #type: SNOWFLAKE
      props:
        sql.show: true
        
        
mybatis:
  configuration:
    map-underscore-to-camel-case: true

        
        
 
      

